2025-05-08 16:36:01,147 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163601-vkvef1y3/logs/debug.log
2025-05-08 16:36:01,147 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163601-vkvef1y3/logs/debug-internal.log
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():789] starting backend
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:36:01,154 INFO    MainThread:50544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:36:01,154 INFO    MainThread:50544 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:36:01,156 INFO    MainThread:50544 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:36:01,156 INFO    MainThread:50544 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:36:01,196 INFO    MainThread:50544 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:36:01,324 WARNING MsgRouterThr:50544 [router.py:message_loop():75] message_loop has been closed
2025-05-08 16:36:01,324 WARNING MsgRouterThr:50544 [router.py:message_loop():75] message_loop has been closed
2025-05-08 16:37:31,517 ERROR   MainThread:50544 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
