2025-05-08 16:31:30,998 INFO    MainThread:50544 [wandb_setup.py:_flush():68] Current SDK version is 0.19.5
2025-05-08 16:31:30,998 INFO    MainThread:50544 [wandb_setup.py:_flush():68] Configure stats pid to 50544
2025-05-08 16:31:30,998 INFO    MainThread:50544 [wandb_setup.py:_flush():68] Loading settings from /Users/kevincorstorphine/.config/wandb/settings
2025-05-08 16:31:30,998 INFO    MainThread:50544 [wandb_setup.py:_flush():68] Loading settings from /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/settings
2025-05-08 16:31:30,998 INFO    MainThread:50544 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-05-08 16:31:30,999 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163130-6nma4ck1/logs/debug.log
2025-05-08 16:31:30,999 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163130-6nma4ck1/logs/debug-internal.log
2025-05-08 16:31:30,999 INFO    MainThread:50544 [wandb_init.py:monkeypatch_ipython():589] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x13b02b690>
2025-05-08 16:31:30,999 INFO    MainThread:50544 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:31:30,999 INFO    MainThread:50544 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:31:30,999 INFO    MainThread:50544 [wandb_init.py:init():789] starting backend
2025-05-08 16:31:31,233 INFO    MainThread:50544 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:31:31,253 INFO    MainThread:50544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:31:31,254 INFO    MainThread:50544 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:31:31,258 INFO    MainThread:50544 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:31:31,259 INFO    MainThread:50544 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:31:31,286 INFO    MainThread:50544 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:31:31,429 ERROR   MainThread:50544 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 957, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-05-08 16:32:22,154 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163222-kfc9qs72/logs/debug.log
2025-05-08 16:32:22,154 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163222-kfc9qs72/logs/debug-internal.log
2025-05-08 16:32:22,155 INFO    MainThread:50544 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:32:22,155 INFO    MainThread:50544 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:32:22,155 INFO    MainThread:50544 [wandb_init.py:init():789] starting backend
2025-05-08 16:32:22,155 INFO    MainThread:50544 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:32:22,159 INFO    MainThread:50544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:32:22,159 INFO    MainThread:50544 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:32:22,161 INFO    MainThread:50544 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:32:22,161 INFO    MainThread:50544 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:32:22,316 INFO    MainThread:50544 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:32:22,440 ERROR   MainThread:50544 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 957, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-05-08 16:32:34,040 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163234-915h093d/logs/debug.log
2025-05-08 16:32:34,040 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163234-915h093d/logs/debug-internal.log
2025-05-08 16:32:34,041 INFO    MainThread:50544 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:32:34,041 INFO    MainThread:50544 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:32:34,041 INFO    MainThread:50544 [wandb_init.py:init():789] starting backend
2025-05-08 16:32:34,041 INFO    MainThread:50544 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:32:34,048 INFO    MainThread:50544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:32:34,049 INFO    MainThread:50544 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:32:34,051 INFO    MainThread:50544 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:32:34,052 INFO    MainThread:50544 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:32:34,113 INFO    MainThread:50544 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:32:34,402 ERROR   MainThread:50544 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 957, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-05-08 16:33:37,250 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163337-ew1k9rau/logs/debug.log
2025-05-08 16:33:37,251 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163337-ew1k9rau/logs/debug-internal.log
2025-05-08 16:33:37,251 INFO    MainThread:50544 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:33:37,252 INFO    MainThread:50544 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:33:37,252 INFO    MainThread:50544 [wandb_init.py:init():789] starting backend
2025-05-08 16:33:37,252 INFO    MainThread:50544 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:33:37,259 INFO    MainThread:50544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:33:37,260 INFO    MainThread:50544 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:33:37,263 INFO    MainThread:50544 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:33:37,264 INFO    MainThread:50544 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:33:37,317 INFO    MainThread:50544 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:34:07,082 WARNING MainThread:50544 [wandb_init.py:init():1465] interrupted
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    result = run_init_handle.wait(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 279, in wait
    found, abandoned = self._slot._get_and_clear(timeout=wait_timeout)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 126, in _get_and_clear
    if self._wait(timeout=timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/lib/mailbox.py", line 122, in _wait
    return self._event.wait(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 629, in wait
    signaled = self._cond.wait(timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.pyenv/versions/3.11.6/lib/python3.11/threading.py", line 331, in wait
    gotit = waiter.acquire(True, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2025-05-08 16:34:22,241 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163422-goku76t2/logs/debug.log
2025-05-08 16:34:22,241 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163422-goku76t2/logs/debug-internal.log
2025-05-08 16:34:22,241 INFO    MainThread:50544 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:34:22,241 INFO    MainThread:50544 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:34:22,242 INFO    MainThread:50544 [wandb_init.py:init():789] starting backend
2025-05-08 16:34:22,242 INFO    MainThread:50544 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:34:22,247 INFO    MainThread:50544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:34:22,248 INFO    MainThread:50544 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:34:22,250 INFO    MainThread:50544 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:34:22,251 INFO    MainThread:50544 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:34:22,405 INFO    MainThread:50544 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:35:52,683 ERROR   MainThread:50544 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-05-08 16:36:01,147 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():637] Logging user logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163601-vkvef1y3/logs/debug.log
2025-05-08 16:36:01,147 INFO    MainThread:50544 [wandb_init.py:setup_run_log_directory():638] Logging internal logs to /Users/kevincorstorphine/Desktop/mli-2025-05-05-coursework/deep_learning.building_neural_networks/wandb/run-20250508_163601-vkvef1y3/logs/debug-internal.log
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():756] calling init triggers
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():761] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():789] starting backend
2025-05-08 16:36:01,148 INFO    MainThread:50544 [wandb_init.py:init():793] sending inform_init request
2025-05-08 16:36:01,154 INFO    MainThread:50544 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-08 16:36:01,154 INFO    MainThread:50544 [wandb_init.py:init():808] backend started and connected
2025-05-08 16:36:01,156 INFO    MainThread:50544 [wandb_run.py:_label_probe_notebook():1196] probe notebook
2025-05-08 16:36:01,156 INFO    MainThread:50544 [wandb_init.py:init():901] updated telemetry
2025-05-08 16:36:01,196 INFO    MainThread:50544 [wandb_init.py:init():926] communicating run to backend with 90.0 second timeout
2025-05-08 16:36:01,324 WARNING MsgRouterThr:50544 [router.py:message_loop():75] message_loop has been closed
2025-05-08 16:36:01,324 WARNING MsgRouterThr:50544 [router.py:message_loop():75] message_loop has been closed
2025-05-08 16:37:31,517 ERROR   MainThread:50544 [wandb_init.py:init():1471] error in wandb.init()
Traceback (most recent call last):
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1461, in init
    return wi.init(run_settings, run_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevincorstorphine/.local/share/virtualenvs/mli-2025-05-05-coursework-rNXVWyyx/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 950, in init
    raise CommError(
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
